CREATE TABLE HowItWorks(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    image_base_path VARCHAR2(100) DEFAULT 'D:\\PROJECTS\\BiteBuddyImages\\HowItWorks\\',
    image_name VARCHAR2(255) NOT NULL,
    caption VARCHAR2(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    user_action VARCHAR2(1000),
    additional_info VARCHAR2(1000),
    tip VARCHAR2(500),
    status VARCHAR2(10) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER UpdateHowItWorksTimestamp
AFTER UPDATE ON HowItWorks
                 FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/


INSERT INTO HowItWorks (image_name, caption, description, status, user_action, additional_info, tip)
VALUES
(
    'browse-menu.jpeg',
    'Browse Menu',
    'Discover a world of delicious meals right at your fingertips! Our easy-to-navigate menu allows you to explore a diverse range of cuisines from local favorites to global delicacies. Whether you’re in the mood for a spicy Indian curry or a classic Italian pasta, we’ve got you covered.',
    'active',
    'Browse through categories, search for specific dishes, or use filters like dietary preferences and price range to refine your selection.',
    'Includes real-time availability updates and recommendations based on your previous orders.',
    'Use the "Recommended for You" section for personalized suggestions based on your taste.'
);

INSERT INTO HowItWorks (image_name, caption, description, status, user_action, additional_info, tip)
VALUES
    (
        'place-order.jpeg',
        'Place Order',
        'Placing an order has never been easier! Select your favorite meals, customize ingredients, and add special instructions to make your order truly yours. With just a few taps, your cravings are on their way!',
        'active',
        'Customize dishes to your liking, add items to the cart, and proceed to checkout. Review the order summary before confirming.',
        'Includes options for group ordering and split payments for shared meals.',
        'Check for available discounts and apply promo codes before completing the order.'
    );

INSERT INTO HowItWorks (image_name, caption, description, status, user_action, additional_info, tip)
VALUES
    (
        'make-payment.jpeg',
        'Make Payment',
        'Enjoy a hassle-free and secure payment experience. Choose from multiple payment methods including credit/debit cards, PayPal, and mobile wallets. Rest assured that all transactions are encrypted and protected.',
        'active',
        'Select a payment method, enter details securely, and confirm payment. You can also save your payment details for faster future transactions.',
        'Supports partial payments, split payments for group orders, and loyalty points redemption.',
        'Double-check the payment summary to ensure all discounts and taxes are correctly applied.'
    );

INSERT INTO HowItWorks (image_name, caption, description, status, user_action, additional_info, tip)
VALUES
    (
        'track-delivery.jpeg',
        'Track Delivery',
        'Stay updated with real-time delivery tracking! Follow your order every step of the way, from preparation at the restaurant to the moment it arrives at your doorstep.',
        'active',
        'Access the tracking screen to view live updates on the order’s status and estimated delivery time. Notifications will keep you informed.',
        'Delivery map includes driver’s location, route progress, and contact details.',
        'Enable push notifications to receive timely updates without checking the app repeatedly.'
    );

INSERT INTO HowItWorks (image_name, caption, description, status, user_action, additional_info, tip)
VALUES
    (
        'receive-order.jpeg',
        'Receive Order',
        'Enjoy contactless delivery for your convenience and safety. Your order will be carefully prepared and delivered to your doorstep with minimal contact, ensuring a seamless experience.',
        'active',
        'Acknowledge receipt of your order in the app and leave feedback if desired.',
        'Includes features like "Delivery photo confirmation" for doorstep drop-offs.',
        'Verify your order against the receipt to ensure everything is as expected.'
    );

INSERT INTO HowItWorks (image_name, caption, description, status, user_action, additional_info, tip)
VALUES
    (
        'order-history.jpeg',
        'Order History',
        'All your previous orders, just a tap away! Quickly find details of past meals, including items ordered, restaurants visited, and payment summaries, for easy reference.',
        'active',
        'Access the order history section to view past orders, reorder meals, or analyze spending patterns.',
        'Ability to filter by date, restaurant, or cuisine.',
        'Bookmark frequent orders to save time on reordering your go-to meals.'
    );

INSERT INTO HowItWorks (image_name, caption, description, status, user_action, additional_info, tip)
VALUES
    (
        'reorder.jpeg',
        'Reorder',
        'Reorder your favorite meals effortlessly! With just a few taps, you can relive your past dining experiences or tweak your old orders for something new.',
        'active',
        'Navigate to past orders, select the desired one, and place the same order or modify it slightly.',
        'Features one-tap reorder buttons and personalized recommendations.',
        'Combine items from multiple previous orders to create a new, custom order.'
    );

INSERT INTO HowItWorks (image_name, caption, description, status, user_action, additional_info, tip)
VALUES
    (
        'contact-support.jpeg',
        'Contact Support',
        'We’re here for you 24/7! Whether it’s an issue with your order, a payment query, or general feedback, our dedicated support team is always ready to assist.',
        'active',
        'Choose between chat, email, or call options to reach customer support instantly.',
        'Multilingual support available for better accessibility.',
        'Prepare detailed information about your issue to ensure a faster resolution process.'
    );
