CREATE TABLE intro_slides(
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
                            image_base_path VARCHAR2(100) DEFAULT 'D:\\PROJECTS\\BiteBuddyImages\\IntroSlides\\',
                            image_name VARCHAR2(255) NOT NULL,
                            caption VARCHAR2(255) NOT NULL,
                            description VARCHAR2(1000) NOT NULL,
                            features VARCHAR2(1000) NOT NULL,
                            keywords VARCHAR2(255),
                            status VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE OR REPLACE TRIGGER UpdateIntroSlideTimestamp
BEFORE UPDATE ON intro_slides
                  FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/         image_name VARCHAR2(255),


INSERT INTO intro_slides (image_name, caption, description, features, keywords)
VALUES
('favorite-food-delivered.jpeg',
 'Your favorite food delivered right to your door!',
 'Welcome to [App Name], where you can enjoy the convenience of ordering food from the best restaurants in town. Whether you’re craving pizza, sushi, or a hearty burger, we’ve got you covered. With easy navigation, secure payments, and fast delivery, ordering food has never been easier.',
 'Quick and easy ordering process, Wide variety of restaurants to choose from, Secure payment gateway, Real-time order tracking',
 'Food delivery, easy ordering, fast delivery, secure payments, restaurant variety');

INSERT INTO intro_slides (image_name, caption, description, features, keywords)
VALUES
    ('top-rated-restaurants.jpeg',
     'Discover top-rated restaurants in your area!',
     'Explore a curated list of local restaurants offering delicious meals. From family favorites to gourmet dining, find restaurants that suit your taste and mood. Enjoy the best food your city has to offer with just a few taps.',
     'User-friendly restaurant search, Customer reviews and ratings, Detailed restaurant menus, Filter options by cuisine, rating, and distance',
     'Local restaurants, food discovery, reviews, restaurant search, food variety');

INSERT INTO intro_slides (image_name, caption, description, features, keywords)
VALUES
    ('real-time-food-tracking.jpeg',
     'Know exactly where your food is!',
     'With our real-time order tracking, you’ll always know the exact location of your delivery. From restaurant preparation to delivery, stay updated every step of the way. No more wondering when your meal will arrive!',
     'Real-time order updates, Delivery driver tracking on the map, Notifications for delivery progress, Estimated delivery time',
     'Order tracking, delivery updates, real-time notifications, map tracking, delivery time');

INSERT INTO intro_slides (image_name, caption, description, features, keywords)
VALUES
    ('exclusive-offers.jpeg',
     'Save big with our exclusive offers!',
     'Enjoy amazing deals, discounts, and limited-time offers. Whether it''s a special promotion, first-time user discount, or seasonal offer, there’s always something to save on. Sign up for notifications so you never miss out on the best deals.',
     'Daily and weekly promotions, Exclusive offers for new users, Notifications for upcoming deals, In-app coupons and voucher codes',
     'Deals, discounts, special offers, promotions, coupons');

INSERT INTO intro_slides (image_name, caption, description, features, keywords)
VALUES
    ('explore-cuisines.jpeg',
     'Explore every cuisine, from Indian to Italian!',
     'Whatever you’re craving, we have a restaurant that serves it. Browse a wide variety of cuisines, including Chinese, Indian, Mexican, Italian, and much more. Satisfy all your food cravings with just a few taps!',
     'Wide range of cuisines, Personalized recommendations, Filter by cuisine type, Multiple food categories (vegan, gluten-free, etc.)',
     'Cuisines, food variety, global dishes, recommendations, personalized menu');

INSERT INTO intro_slides (image_name, caption, description, features, keywords)
VALUES
    ('secure-payments.jpeg',
     'Pay your way, with secure and simple options.',
     'Choose from multiple payment options to pay for your order. Whether it’s through credit cards, debit cards, PayPal, or in-app wallet, we make sure your payment process is smooth and secure. Enjoy peace of mind with encrypted transactions.',
     'Credit/debit card payments, PayPal and mobile wallet support, Secure payment gateway, Easy one-click payment for future orders',
     'Payment options, secure payments, credit card, PayPal, mobile wallet');

INSERT INTO intro_slides (image_name, caption, description, features, keywords)
VALUES
    ('favorite-meals.jpeg',
     'Never forget your favorite meals again!',
     'With [App Name], you can save your favorite restaurants and orders for quick access. No need to search again — simply tap to reorder your go-to meals or easily browse through your saved places.',
     'Save favorite restaurants, Reorder previous meals, Create personalized meal lists, Quick access to saved orders',
     'Favorites, quick access, reorder, personalized meals, saved restaurants');

INSERT INTO intro_slides (image_name, caption, description, features, keywords)
VALUES
    ('contactless-delivery.jpeg',
     'Safe, secure, and contactless delivery.',
     'In response to current events, we offer contactless delivery to ensure your safety and comfort. Your driver will leave your food at your doorstep, ensuring a seamless and contact-free experience from start to finish.',
     'Contactless delivery option, No need to sign for your order, Driver leaves food at your doorstep, Enhanced hygiene protocols',
     'Contactless delivery, safety, hygiene, doorstep delivery, secure process');

INSERT INTO intro_slides (image_name, caption, description, features, keywords)
VALUES
    ('customer-support.jpeg',
     'We’re here for you, anytime.',
     'Have questions or need assistance? Our customer support team is available 24/7 to help you with anything you need. Whether it’s an order issue, a payment query, or a general inquiry, we’ve got you covered with prompt and friendly service.',
     '24/7 customer support, Easy access to chat, email, and phone support, Order resolution and refunds, Friendly and helpful agents',
     'Customer support, 24/7 service, assistance, inquiries, resolution');

INSERT INTO intro_slides (image_name, caption, description, features, keywords)
VALUES
    ('download-the-app.jpeg',
     'Download the app and enjoy fast, delicious meals today!',
     'Ready to get started? Download [App Name] now and enjoy fast, convenient food delivery to your door. With a variety of restaurants, exclusive offers, and seamless service, you’re only a few taps away from your next meal.',
     'Easy app download, Fast and reliable service, Multiple restaurant choices, Exclusive in-app deals, Seamless user experience',
     'App download, food delivery, fast service, exclusive deals, restaurant variety');
