CREATE TABLE Chefs_Special_Slides (
                                      slide_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
                                      slideshow_id NUMBER NOT NULL,
                                      image_url VARCHAR2(255) NOT NULL,
                                      caption VARCHAR2(200) NOT NULL, -- Dish name
                                      description CLOB, -- Description of the dish
                                      chef_quote VARCHAR2(255), -- Chef’s special quote about the dish
                                      display_order NUMBER,
                                      start_date TIMESTAMP WITH TIME ZONE,
                                      end_date TIMESTAMP WITH TIME ZONE,
                                      status VARCHAR2(10) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
                                      FOREIGN KEY (slideshow_id) REFERENCES Slideshows(slideshow_id) ON DELETE CASCADE
);
