CREATE TABLE Customer_Reviews_Slides (
                                         slide_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
                                         slideshow_id NUMBER NOT NULL,
                                         image_url VARCHAR2(255), -- Reviewer’s image (optional)
                                         caption VARCHAR2(200) NOT NULL, -- Review text
                                         description CLOB, -- Additional comments or feedback
                                         reviewer_name VARCHAR2(100), -- Name of the reviewer
                                         rating NUMBER(1,1) CHECK (rating BETWEEN 1 AND 5), -- Rating out of 5
                                         product_or_service VARCHAR2(100), -- Product or service being reviewed
                                         display_order NUMBER,
                                         start_date TIMESTAMP WITH TIME ZONE,
                                         end_date TIMESTAMP WITH TIME ZONE,
                                         status VARCHAR2(10) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
                                         FOREIGN KEY (slideshow_id) REFERENCES Slideshows(slideshow_id) ON DELETE CASCADE
);
