CREATE TABLE SLIDESHOWS (
                            slideshow_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
                            name VARCHAR2(100) NOT NULL UNIQUE,
                            description CLOB,
                            status VARCHAR2(10) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER update_slideshows_timestamp
AFTER UPDATE ON Slideshows
                  FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

INSERT INTO SLIDESHOWS (NAME, DESCRIPTION) VALUES ('Intro Slideshow', 'A slideshow that provides a visual overview of the food delivery app, showcasing key features and benefits');
INSERT INTO SLIDESHOWS (NAME, DESCRIPTION) VALUES ('Featured Dishes Slideshow', 'A slideshow highlighting top-rated dishes from various restaurants, featuring enticing food images');
INSERT INTO SLIDESHOWS (NAME, DESCRIPTION) VALUES ('Top Discounts Slideshow', 'A slideshow promoting current discounts and offers on popular menu items across different restaurants');
INSERT INTO SLIDESHOWS (NAME, DESCRIPTION) VALUES ('Video Slideshow', 'A video-based slideshow that presents short clips of restaurant kitchens, chefs, and customer reviews to engage viewers');
INSERT INTO SLIDESHOWS (NAME, DESCRIPTION) VALUES ('How It Works Slideshow', 'A slideshow explaining the ordering process, from browsing menus to delivery, making it easy for new users');
INSERT INTO SLIDESHOWS (NAME, DESCRIPTION) VALUES ('Chef’s Special Slideshow', 'A slideshow showcasing exclusive or seasonal dishes created by top chefs, with a focus on unique flavors and ingredients');
INSERT INTO SLIDESHOWS (NAME, DESCRIPTION) VALUES ('Customer Reviews Slideshow', 'A slideshow of customer testimonials and ratings for popular restaurants and dishes, to build trust and engagement');
