CREATE TABLE Top_Discounts_Slides (
                                      slide_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
                                      slideshow_id NUMBER NOT NULL,
                                      image_url VARCHAR2(255) NOT NULL,
                                      caption VARCHAR2(200) NOT NULL, -- Discount title
                                      description CLOB, -- Description of the offer
                                      discount_amount NUMBER(5,2), -- Discount percentage or amount
                                      promo_code VARCHAR2(50), -- Promo code for the discount
                                      link_url VARCHAR2(255), -- Link for the promotion
                                      display_order NUMBER,
                                      start_date TIMESTAMP WITH TIME ZONE,
                                      end_date TIMESTAMP WITH TIME ZONE,
                                      status VARCHAR2(10) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
                                      FOREIGN KEY (slideshow_id) REFERENCES Slideshows(slideshow_id) ON DELETE CASCADE
);
